[build]
  command = "pnpm run build"
  publish = "dist"

[build.environment]
  NODE_VERSION = "18"

# Ensure SPA routing works correctly
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = true 